version: '3.5'

services:
  develop-adminer:
    container_name: develop-adminer-container
    hostname: develop-adminer-server
    image: adminer
    ports:
      - "${ADMINER_SERVER_PORT}:8080"
    networks:
      - develop-link

  develop-mysql:
    container_name: develop-db-container
    hostname: develop-db-server
    image: mariadb:10.5.10
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - "${MYSQL_SERVER_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_INITIAL_DATABASE}"
      - "MYSQL_USER=${MYSQL_INITIAL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_INITIAL_PASS}"
    networks:
      - develop-link

  develop-mailpit:
    image: 'axllent/mailpit:v1.6'
    ports:
      - '${MAILPIT_SERVER_SMTP_PORT:-1025}:1025'
      - '${MAILPIT_SERVER_FRONT_PORT:-8025}:8025'
    networks:
      - develop-link

networks:
  develop-link:
    name: develop.internal
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"