version: '3.5'

services:
  develop-php72:
    container_name: develop-web-container72
    hostname: develop-web-server
    build:
      context: ./php
      dockerfile: Dockerfile.php72
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/msmtprc:/etc/msmtprc
      - ./php/apache2.conf:/etc/apache2/apache2.conf
      - ./php/mods-enabled/vhost_alias.load://etc/apache2/mods-enabled/vhost_alias.load
      - ./php/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/sites-enabled/001-virtual.conf:/etc/apache2/sites-enabled/001-virtual.conf
      - ./php/log:/var/log/apache2
      - "${WEB_SERVER_DIR}:/var/www/vhosts"
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - develop-link