version: '3.5'

services:
  develop-php:
    container_name: develop-web-container
    hostname: develop-web-server
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/msmtprc:/etc/msmtprc
      - ./php/apache2.conf:/etc/apache2/apache2.conf
      - ./php/mods-enabled/vhost_alias.load://etc/apache2/mods-enabled/vhost_alias.load
      - ./php/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/sites-enabled/001-virtual.conf:/etc/apache2/sites-enabled/001-virtual.conf
      - ./php/log:/var/log/apache2
      - "${WEB_SERVER_DIR}:/var/www/vhosts"
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - develop-link

  develop-adminer:
    container_name: develop-adminer-container
    hostname: develop-adminer-server
    image: adminer
    ports:
      - "${ADMINER_SERVER_PORT}:8080"
    networks:
      - develop-link

  develop-mysql:
    container_name: develop-db-container
    hostname: develop-db-server
    image: mariadb:10.5.10
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports:
      - "${MYSQL_SERVER_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_INITIAL_DATABASE}"
      - "MYSQL_USER=${MYSQL_INITIAL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_INITIAL_PASS}"
    networks:
      - develop-link

  develop-mail:
    container_name: develop-mail-container
    hostname: develop-mail-server
    build:
      context: ./maildev
      dockerfile: Dockerfile
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_SERVER_PORT}:80"
    networks:
      - develop-link

networks:
  develop-link:
    name: develop.internal
    ipam:
      driver: default
      config:
        - subnet: "172.28.0.0/24"