FROM php:5.6-apache

RUN apt-get update \
  && apt-get install -y\
      zlib1g-dev\
      libzip-dev\
      libpng-dev\
      libjpeg-dev\
      libfreetype6-dev\
      libwebp-dev\
      msmtp\
  && docker-php-ext-install zip pdo_mysql mysqli mbstring\
  && apt-get autoremove -y \
  && apt-get clean -y

RUN docker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr
RUN docker-php-ext-install gd

WORKDIR /var/www
RUN a2enmod rewrite